[project]
authors = ["Sébastien Boisgérault <Sebastien.Boisgerault@gmail.com>"]
channels = ["conda-forge"]
name = "auto-mpg-better"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks.clean]
cmd = """\
    rm -rf article.pdf article.html
    rm -rf images/*.png
    rm -rf notebook.ipynb
    """

[tasks.exec]
cmd = "jupyter execute --output=notebook.ipynb notebook-src.ipynb"
inputs = ["auto-mpg.csv", "notebook-src.ipynb"]
outputs = ["notebook.ipynb", "images/prediction.png", "images/error.png"]

[tasks.build]
cmd = """pandoc 
  --citeproc 
  --pdf-engine=tectonic 
  --bibliography=references.bib 
  -o article.pdf 
  article.md
"""
inputs = ["article.md", "references.bib", "images/prediction.png", "images/error.png"]
outputs = ["article.pdf"]
depends-on = ["exec"]

[tasks.html]
cmd = """pandoc 
  --standalone 
  --citeproc 
  --bibliography=references.bib 
  -o article.html 
  article.md
"""
inputs = ["article.md", "references.bib", "images/prediction.png", "images/error.png"]
outputs = ["article.pdf"]
depends-on = ["exec"]

[tasks.all]
depends-on = ["build", "html"]

[dependencies]
python = ">=3.13.2,<3.14"
jupyterlab = ">=4.3.5,<5"
marimo = ">=0.11.9,<0.12"
matplotlib = ">=3.10.0,<4"
numpy = ">=2.2.3,<3"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
pandoc = ">=3.6.3,<4"
tectonic = ">=0.15.0,<0.16"
